// -------------------------------------------------------------------
// Generated by 365admin-publish 
// Service wrapper  v1
// -------------------------------------------------------------------
/*
---
title: Page Info
---
*/
package cmds
import (
"context"
"encoding/json"
"os"
"path"
"github.com/nats-io/nats.go"
"github.com/nats-io/nats.go/micro"
"github.com/spf13/cobra"
"github.com/365admin/sharepoint-governance/schemas"
"github.com/365admin/sharepoint-governance/execution"
"github.com/365admin/sharepoint-governance/utils"
)
func SharepointPageinfoPost(ctx context.Context, body []byte,args  []string)  ( *schemas.PageinfoResponse, error) {
inputErr := os.WriteFile(path.Join(utils.WorkDir("sharepoint-governance"), "pageinfo.request.json"), body, 0644)
if inputErr != nil {
	return nil,inputErr
}

_, pwsherr := execution.ExecutePowerShell("john","*","sharepoint-governance","30-sharepoint","pageinfo.ps1","" )
if (pwsherr != nil) {
	return nil,pwsherr
}

resultingFile := path.Join(utils.WorkDir("sharepoint-governance"), "pageinfo.response.json")
data, err := os.ReadFile(resultingFile)
if (err != nil) {
	return nil,err
}
resultObject := schemas.PageinfoResponse{}
err = json.Unmarshal(data, &resultObject)
return &resultObject,nil

	
// end result mapping

func init(){
	
}
}
