// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Page Info
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/365admin/sharepoint-governance/execution"
	"github.com/365admin/sharepoint-governance/schemas"
	"github.com/365admin/sharepoint-governance/utils"
)

func SharepointPageinfoPost() usecase.Interactor {
	type Request struct {
		Body schemas.PageinfoRequest `json:"body" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *schemas.PageinfoResponse) error {
		body, inputErr := json.Marshal(input.Body)
		if inputErr != nil {
			return inputErr
		}

		inputErr = os.WriteFile(path.Join(utils.WorkDir("sharepoint-governance"), "pageinfo.request.json"), body, 0644)
		if inputErr != nil {
			return inputErr
		}

		_, err := execution.ExecutePowerShell("john", "*", "sharepoint-governance", "30-sharepoint", "pageinfo.ps1", "")
		if err != nil {
			return err
		}

		resultingFile := path.Join(utils.WorkDir("sharepoint-governance"), "pageinfo.response.json")
		data, err := os.ReadFile(resultingFile)
		if err != nil {
			return err
		}
		resultObject := schemas.PageinfoResponse{}
		err = json.Unmarshal(data, &resultObject)
		*output = resultObject
		return err

	})
	u.SetTitle("Page Info")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("SharePoint")
	return u
}
